package com.unity3d.player;
public final class Config {
	public static final String  gameConfig = "W3siQXBwU2VydmVyIjpbImh0dHA6Ly8xMC4yMy4yMy40NTo4MDgwLyJdLCJBcHBWZXJzaW9uIjoiMC4wLjAiLCJGbGFnIjoiUmVsZWFzZSIsIlJhbmRvbUNvZGUiOm51bGwsIkJ1aWxkVGltZSI6bnVsbCwiUHJvZHVjdE5hbWUiOm51bGwsIkFwcGxpY2F0aW9uSWQiOm51bGwsIlZlcnNpb25Db2RlIjpudWxsLCJWZXJzaW9uTmFtZSI6bnVsbCwiR3JheVBhY2thZ2UiOm51bGx9XQ==";
}